### ISSUE TITLE
improve elastaticsearch

### ISSUE THREAD

**Issue by qiaofeng1227** [websoft9dev/role_elasticsearch#4]
1. multiple versions(support 6.x)
2. remote开启
3. Notes记录
4. 增加变量端口
5. elasticsearch_meta移动到vars的main.yml

**Comment by hnczhjh** [comment]
### elasticesearch-oss6.x/7.x 最新可用版本如下：
elasticsearch-oss |     7.10.2 | https://artifacts.elastic.co/packages/oss-7.x/apt stable/main amd64 Packages
elasticsearch-oss |      7.9.3 | https://artifacts.elastic.co/packages/oss-7.x/apt stable/main amd64 Packages
elasticsearch-oss |      7.8.1 | https://artifacts.elastic.co/packages/oss-7.x/apt stable/main amd64 Packages
elasticsearch-oss |      7.7.1 | https://artifacts.elastic.co/packages/oss-7.x/apt stable/main amd64 Packages
elasticsearch-oss |      7.6.2 | https://artifacts.elastic.co/packages/oss-7.x/apt stable/main amd64 Packages
elasticsearch-oss |      7.5.2 | https://artifacts.elastic.co/packages/oss-7.x/apt stable/main amd64 Packages
elasticsearch-oss |      7.4.2 | https://artifacts.elastic.co/packages/oss-7.x/apt stable/main amd64 Packages
elasticsearch-oss |      7.3.2 | https://artifacts.elastic.co/packages/oss-7.x/apt stable/main amd64 Packages
elasticsearch-oss |      7.2.1 | https://artifacts.elastic.co/packages/oss-7.x/apt stable/main amd64 Packages
elasticsearch-oss |      7.1.1 | https://artifacts.elastic.co/packages/oss-7.x/apt stable/main amd64 Packages
elasticsearch-oss |      7.0.1 | https://artifacts.elastic.co/packages/oss-7.x/apt stable/main amd64 Packages
elasticsearch-oss |     6.8.17 | https://artifacts.elastic.co/packages/oss-6.x/apt stable/main amd64 Packages
elasticsearch-oss |      6.7.2 | https://artifacts.elastic.co/packages/oss-6.x/apt stable/main amd64 Packages
elasticsearch-oss |      6.6.2 | https://artifacts.elastic.co/packages/oss-6.x/apt stable/main amd64 Packages
elasticsearch-oss |      6.5.4 | https://artifacts.elastic.co/packages/oss-6.x/apt stable/main amd64 Packages
elasticsearch-oss |      6.4.3 | https://artifacts.elastic.co/packages/oss-6.x/apt stable/main amd64 Packages
elasticsearch-oss |      6.3.2 | https://artifacts.elastic.co/packages/oss-6.x/apt stable/main amd64 Packages

**Comment by hnczhjh** [comment]
### 修改elasticsearch.yml开启remote
```
# ---------------------------------- Network -----------------------------------
#
# Set the bind address to a specific IP (IPv4 or IPv6):
#
network.host: 0.0.0.0
#
# Set a custom port for HTTP:
#
http.port: 9200
#
# For more information, consult the network module documentation.
```

**Comment by qiaofeng1227** [comment]
1. amazonliux test
2. test magento(it has role_elastic)
