### ISSUE TITLE
add login-web-page for elasticsearch

### ISSUE THREAD

**Issue by geraintlyu** [websoft9dev/role_elasticsearch#6]
when visit htttp://ip:5601,we can't get the login web page.

**Comment by qiaofeng1227** [comment]
curl -H "Content-Type:application/json" -XPOST -u elastic 'http://127.0.0.1:9200/_xpack/security/user/elastic/_password' -d '{ "password" : "123456" }'

**Comment by qiaofeng1227** [comment]
vim elasticsearch.yml and restart elastic service
```
xpack.security.enabled: true
xpack.license.self_generated.type: basic
xpack.security.transport.ssl.enabled: true
```

**Comment by qiaofeng1227** [comment]
oss version have no login-page
